sonar.projectKey= "Aquí va el nombre de tu proyecto en SonarQube, por ejemplo: EcoEnergyBackend"
sonar.host.url= "Aquí va la URL de tu servidor SonarQube, por ejemplo: http://localhost:9000"
sonar.token = "Aquí va tu token de SonarQube"

sonar.sources=.

sonar.python.version = 3.12.2
sonar.python.coverage.reportPaths=coverage.xml

# Limpieza
sonar.exclusions=venv/*,_pycache_/,tests/*,node_modules/**,.next/**,coverage/**
