# ==========================
# 1️⃣ CONFIGMAP DE MOSQUITTO
# ==========================

apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  labels:
    app: mosquitto
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    listener 9001
    protocol websockets

---
# ==========================
# 2️⃣ DEPLOYMENT DE MOSQUITTO
# ==========================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config

---
# ==========================
# 3️⃣ SERVICE DE MOSQUITTO
# ==========================

apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    app: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: websocket
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP
